### ISSUE TITLE
Main rss feed generates broken links

### ISSUE THREAD

**Issue by manuelhaussmann** [mlresearch/mlresearch.github.io#1]
The RSS feed of the volumes (http://proceedings.mlr.press/feed.xml) is broken insofar as the links it generates are missing a slash. 

For example for the first volume the item is 
```
<item>
<title>v1</title>
<description>Gaussian Processes in Practice</description>
<link>http://proceedings.mlr.pressv1</link>
<guid isPermaLink="true">http://proceedings.mlr.press/v1</guid>
</item>
```
Instead of `<link>http://proceedings.mlr.press/v1</link>`.

Since the guid below is correct, it seems that the link is simply missing the `prepend: '/' in the `/assets/rss/feed.xml` file:
```
<link>{{ repository.name | prepend: site.baseurl | prepend: site.url }}</link>
<guid isPermaLink="true">{{ repository.name | prepend: '/' | prepend: site.baseurl | prepend: site.url }}</guid>
```

**Comment by lawrennd** [comment]
Thanks @manuelhaussmann !

The relevant code is now in http://github.com/lawrennd/proceedings at assets/rss/feed.xml 

Would you be happy to submit a pull request there?

**Comment by manuelhaussmann** [comment]
> Would you be happy to submit a pull request there?

Sure. What exactly is the relationship to the new repository? Do I see it correctly, that it is used both for the general proceedings site as well as the individual volumes? Because within a volume the feed works as desired, it only fails for the main feed.

**Comment by lawrennd** [comment]
Sorry for delayed reply Manuel. 

The new repo is a 'jekyll remote theme' that is applied to the whole site as you suggest. 

I'll take a look though because it sounds like this is specific to the main site.

**Comment by lawrennd** [comment]
Yes, you're totally right, it's the main site specific repo that's at fault. I've found the file and made the change you suggest. Thanks for highlighting!
