### ISSUE TITLE
Certificate Issue when accessing via HTTPs

### ISSUE THREAD

**Issue by p16i** [mlresearch/mlresearch.github.io#2]
At the moment, it seems that the site has a certificate issue when accessing via `HTTPS`.

<img width="314" alt="image" src="https://user-images.githubusercontent.com/1214890/117116322-826bdb80-ad8e-11eb-8e54-d7c36e59086f.png">

The current certificate seems to belong to `www.github.com`.

<img width="461" alt="image" src="https://user-images.githubusercontent.com/1214890/117116553-c959d100-ad8e-11eb-88e8-672198a7e775.png">

I checked on both Safari and Chrome; they have the same issue. I access the site from Germany.

**Comment by lawrennd** [comment]
Thanks for this. I think it’s fixed now, apologies for not closing earlier.
