### ISSUE TITLE
AISTATS 2022 proceedings not available from the main page

### ISSUE THREAD

**Issue by manuelhaussmann** [mlresearch/mlresearch.github.io#4]
The proceedings of AISTATS 2022 are only available via the direct link, and not listed on the main site (https://proceedings.mlr.press/) yet. 
Probably just missing a compilation of the main site as the last update (2022-04-25) there is from before the proceedings became available (2022-05-03).

(Thanks for maintaining the proceedings!)

**Comment by lawrennd** [comment]
Thanks Manuel, you're right it should appear when the static site is recompiled. I'll trigger it today. Thanks for spotting!
