### ISSUE TITLE
Link in example `citeproc` is broken

### ISSUE THREAD

**Issue by Pseudomanifold** [mlresearch/mlresearch.github.io#8]
The link pointing towards `citeproc` examples is broken: https://blog.martinfenner.org/2013/07/30/citeproc-yaml-for-bibliographies/

I think the content can be accessed via: https://blog.front-matter.io/posts/citeproc-yaml-for-bibliographies/

**Comment by lawrennd** [comment]
Thanks for picking this up Bastian! I'll update the link in the generating code now so this error doesn't propagate. (it's in the papersite repo as ruby/mlreseasrch.rb).

**Comment by Pseudomanifold** [comment]
Awesome, thanks so much! Did not know where to find this actually :sweat_smile:

**Comment by lawrennd** [comment]
I should make it clearer where it is ... but code's so embarrassing maybe I subconsciously don't want anyone to know!

**Comment by Pseudomanifold** [comment]
I think it's great that this code exists at all, and I very much appreciate any work on this :smile:  No need to be embarrassed—it's rather the commercial publishers that should be embarrassed because their websites don't even work most of the time :wink:
